// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMpS52Q32Yo4nvNx5hy8CSAbOUrMgGlJo',
    appId: '1:629023836355:web:301b803cc2d018dff97a76',
    messagingSenderId: '629023836355',
    projectId: 'insideout-4cd8d',
    authDomain: 'insideout-4cd8d.firebaseapp.com',
    storageBucket: 'insideout-4cd8d.firebasestorage.app',
    measurementId: 'G-Z25G1G4BK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz26sPljP7wQGDq9N6_OS4GEyrVXLoU6c',
    appId: '1:629023836355:android:432d3d46686f850ff97a76',
    messagingSenderId: '629023836355',
    projectId: 'insideout-4cd8d',
    storageBucket: 'insideout-4cd8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmjMCszRoaJ60nFYrqoPGfK5Vy87QxVlg',
    appId: '1:629023836355:ios:6ea6be020795573ff97a76',
    messagingSenderId: '629023836355',
    projectId: 'insideout-4cd8d',
    storageBucket: 'insideout-4cd8d.firebasestorage.app',
    iosBundleId: 'org.aossie.neurotrack.patient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmjMCszRoaJ60nFYrqoPGfK5Vy87QxVlg',
    appId: '1:629023836355:ios:6ea6be020795573ff97a76',
    messagingSenderId: '629023836355',
    projectId: 'insideout-4cd8d',
    storageBucket: 'insideout-4cd8d.firebasestorage.app',
    iosBundleId: 'org.aossie.neurotrack.patient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMpS52Q32Yo4nvNx5hy8CSAbOUrMgGlJo',
    appId: '1:629023836355:web:249a8053fd17e770f97a76',
    messagingSenderId: '629023836355',
    projectId: 'insideout-4cd8d',
    authDomain: 'insideout-4cd8d.firebaseapp.com',
    storageBucket: 'insideout-4cd8d.firebasestorage.app',
    measurementId: 'G-VNPSKV5RQB',
  );
}
